# Generated by Django 4.2 on 2023-04-26 16:28

import board.logic.logic
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_pos_x', models.IntegerField()),
                ('from_pos_y', models.IntegerField()),
                ('to_pos_x', models.IntegerField()),
                ('to_pos_y', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chessman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('type', models.CharField(choices=[('PAWN', board.logic.logic.PawnLogic), ('ROOK', board.logic.logic.RookLogic), ('KNIGHT', board.logic.logic.KnightLogic), ('BISHOP', board.logic.logic.BishopLogic), ('KING', board.logic.logic.KnightLogic), ('QUEEN', board.logic.logic.KnightLogic)], max_length=32)),
                ('color', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black')], max_length=5)),
                ('movements', models.ManyToManyField(to='board.movement')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chessmans', models.ManyToManyField(to='board.chessman')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
